# Generated by Django 2.0.3 on 2019-05-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=140)),
                ('temp', models.FloatField()),
                ('temp_type', models.CharField(choices=[('R', 'Real'), ('F', 'Feels')], max_length=1)),
                ('cloudCover', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('point_type', models.CharField(choices=[('N', 'Now'), ('H', 'Hourly'), ('D', 'Daily')], max_length=1)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='weather_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_now', models.CharField(max_length=140)),
                ('sum_day', models.CharField(max_length=140)),
                ('sum_week', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='weatherCast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
