# Generated by Django 2.0.3 on 2018-03-27 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AName', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='LPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LName', models.CharField(max_length=140)),
                ('LRange', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MName', models.CharField(max_length=140)),
                ('MRange', models.IntegerField()),
                ('NumMark', models.IntegerField()),
                ('NormMark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Range', models.IntegerField()),
                ('AWeight', models.IntegerField()),
                ('IdAlt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_TItaP.Alternative')),
                ('IdLPR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_TItaP.LPR')),
            ],
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdAlt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_TItaP.Alternative')),
                ('IdMark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_TItaP.Mark')),
            ],
        ),
        migrations.CreateModel(
            name='Сriterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=140)),
                ('CRange', models.IntegerField()),
                ('CWeight', models.IntegerField()),
                ('CType', models.CharField(max_length=140)),
                ('OptimType', models.CharField(max_length=140)),
                ('EdIzmer', models.CharField(max_length=140)),
                ('ScaleType', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='IdCrit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_TItaP.Сriterion'),
        ),
    ]
