# Generated by Django 2.0.3 on 2018-03-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_TItaP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpr',
            name='LRange',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='IdCrit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='university_TItaP.Сriterion'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='MName',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='mark',
            name='MRange',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='NormMark',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='NumMark',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='AWeight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='IdAlt',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='university_TItaP.Alternative'),
        ),
        migrations.AlterField(
            model_name='result',
            name='IdLPR',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='university_TItaP.LPR'),
        ),
        migrations.AlterField(
            model_name='result',
            name='Range',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='IdAlt',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='university_TItaP.Alternative'),
        ),
        migrations.AlterField(
            model_name='vector',
            name='IdMark',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='university_TItaP.Mark'),
        ),
        migrations.AlterField(
            model_name='сriterion',
            name='CRange',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='сriterion',
            name='CType',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='сriterion',
            name='CWeight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='сriterion',
            name='EdIzmer',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='сriterion',
            name='OptimType',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='сriterion',
            name='ScaleType',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
