# Generated by Django 2.0.3 on 2018-04-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_TItaP', '0002_auto_20180327_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vector',
            options={'ordering': ['IdMark']},
        ),
    ]
