# Generated by Django 2.0.3 on 2019-03-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlanetaKino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('posterIMG', models.CharField(max_length=140)),
                ('href', models.CharField(max_length=140)),
                ('date', models.CharField(max_length=20)),
                ('inTheater', models.BooleanField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
