# Generated by Django 2.0.3 on 2019-07-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=14)),
                ('value', models.CharField(max_length=1400)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
