# Generated by Django 2.0.3 on 2018-03-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedUpdate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chapters',
            new_name='bookUpdate',
        ),
        migrations.AlterModelOptions(
            name='bookupdate',
            options={'ordering': ['datetime']},
        ),
    ]
