# Generated by Django 2.0.3 on 2018-03-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedUpdate', '0002_auto_20180318_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookupdate',
            options={'ordering': ['-datetime']},
        ),
    ]
