# Generated by Django 2.0.3 on 2018-04-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedUpdate', '0003_auto_20180318_2113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookUpdate',
            new_name='feedUpdate',
        ),
    ]
