# Generated by Django 2.0.3 on 2019-02-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedUpdate', '0004_auto_20180402_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=42)),
                ('title_full', models.CharField(max_length=140)),
                ('href', models.CharField(max_length=420)),
                ('href_title', models.CharField(max_length=420)),
                ('emojis', models.CharField(max_length=7)),
                ('filter', models.CharField(max_length=140)),
                ('delay', models.IntegerField()),
            ],
            options={
                'ordering': ['title_full'],
            },
        ),
        migrations.AlterField(
            model_name='feedupdate',
            name='href',
            field=models.CharField(max_length=420),
        ),
        migrations.AlterField(
            model_name='feedupdate',
            name='title',
            field=models.CharField(max_length=42),
        ),
    ]
