# Generated by Django 2.0.3 on 2019-02-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedUpdate', '0005_auto_20190216_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedupdate',
            name='href',
            field=models.CharField(max_length=210),
        ),
    ]
