# Generated by Django 2.0.3 on 2019-02-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedUpdate', '0006_auto_20190216_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='delay',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='emojis',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='filter',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='href_title',
            field=models.CharField(max_length=420, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title_full',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
