# Generated by Django 2.0.3 on 2019-06-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedUpdate', '0008_auto_20190302_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedupdate',
            name='href',
            field=models.CharField(max_length=420),
        ),
    ]
