# Generated by Django 2.0.3 on 2019-09-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedUpdate', '0009_auto_20190625_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedupdate',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='feedupdate',
            name='href',
            field=models.CharField(db_index=True, max_length=420),
        ),
        migrations.AlterField(
            model_name='feedupdate',
            name='name',
            field=models.CharField(db_index=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='feedupdate',
            name='title',
            field=models.CharField(db_index=True, max_length=42),
        ),
    ]
