# Generated by Django 2.0.3 on 2019-06-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=42)),
                ('title_full', models.CharField(max_length=140)),
                ('href', models.CharField(max_length=420)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=42)),
                ('description', models.CharField(max_length=420)),
                ('href', models.CharField(max_length=420)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
