# Generated by Django 2.0.3 on 2019-06-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='emojis',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
