# Generated by Django 2.0.3 on 2019-06-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenda', '0002_calendar_emojis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='start',
        ),
        migrations.AddField(
            model_name='event',
            name='calendar',
            field=models.CharField(default='lost', max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
