# Generated by Django 2.0.3 on 2019-06-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenda', '0003_auto_20190612_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=420, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='href',
            field=models.CharField(max_length=420, null=True),
        ),
    ]
