from .models import feed

'''
    feed(
        title='',
        title_full='',
        href='',
        href_title='',
        emojis='',
        delay=1
    ),
'''

# rss generator available at https://feedfry.com

# emojis
# 🏮 - hide from feeds
# 💎 - inIndex=True
# 🗃️ - inIndex=False
# 👤 — my activities
# 🏋️ — fitness

feeds = (
    feed(
        title='Скульптор',
        title_full='Легендарный Лунный Скульптор',
        href='http://xn--80ac9aeh6f.xn--p1ai/legendary-moonlight-sculptor/',
        emojis='💎'
    ),
    feed(
        title='RenegadeImmortal',
        title_full='Renegade Immortal',
        href='https://www.wuxiaworld.com/feed/chapters/renegade-immortal',
        href_title='https://www.wuxiaworld.com/novel/renegade-immortal',
        emojis='💎'
    ),
    feed(
        title='EvilGod',
        title_full='Heaven Defying Evil God',
        href='https://www.wuxiaworld.com/feed/chapters/against-the-gods',
        href_title='https://www.wuxiaworld.com/novel/against-the-gods',
        emojis='💎'
    ),
    feed(
        title='Gamer',
        title_full='The Gamer',
        href='feed://www.webtoons.com/en/fantasy/the-gamer/rss?title_no=88',
        href_title='https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88&page=1',
        emojis='💎'
    ),
    feed(
        title='Ляпота',
        title_full="It's a good trip",
        href='https://www.youtube.com/channel/UCeHB0mXXj_kyPCB-yRr8b9w/videos',
        emojis='💎'
    ),
    feed(
        title='GCN',
        title_full="Global Cycling Network",
        href='https://www.youtube.com/channel/UCuTaETsuCOkJ0H_GAztWt0Q/videos',
        emojis='💎'
    ),
    feed(
        title='GCNTech',
        title_full="GCN Tech",
        href='https://www.youtube.com/channel/UC710HJmp-YgNbE5BnFBRoeg/videos',
    ),
    feed(
        title='KeddrYT',
        title_full='Keddr.com (YouTube)',
        href='https://www.youtube.com/channel/UCSpU8Y1aoqBSAwh8DBpiM9A/videos',
        emojis='💎'
    ),
    feed(
        title='KeddrPlus',
        href='https://www.youtube.com/channel/UCB3_rmcc7oZ6Tdfe104rPNQ/videos',
        emojis='💎'
    ),
    feed(
        title='VeddroYT',
        title_full='Veddro.com (YouTube)',
        href='https://www.youtube.com/channel/UCItSim1k6hOHyogg1LJ0JCQ/videos',
    ),
    feed(
        title='ZaddrotYT',
        title_full='Zaddrot.com (YouTube)',
        href='https://www.youtube.com/channel/UCjQb9npdMq_u1rRBgoQ24fg/videos',
        emojis='💎'
    ),
    feed(
        title='Kurzgesagt',
        title_full='Kurzgesagt – In a Nutshell',
        href='https://www.youtube.com/channel/UCsXVk37bltHxD1rDPwtNM8Q/videos',
        emojis='💎'
    ),
    feed(
        title='LastWeekTonight',
        title_full='Last Week Tonight with John Oliver',
        href='https://www.youtube.com/channel/UC3XTzVzaHQEd30rQbuvCtTQ/videos',
        emojis='💎'
    ),
    feed(
        title='Linus',
        title_full='Linus Tech Tips',
        href='https://www.youtube.com/channel/UCXuqSBlHAE6Xw-yeJA0Tunw/videos',
        emojis='💎'
    ),
    feed(
        title='TechLinked',
        title_full='Tech Linked by Linus',
        href='https://www.youtube.com/channel/UCeeFfhMcJa1kjtfZAGskOCA/videos',
        emojis='💎'
    ),
    feed(
        title='Techquickie',
        href='https://www.youtube.com/channel/UC0vBXGSyV14uvJ4hECDOl0Q/videos',
    ),
    feed(
        title='SuperFun',
        title_full='Channel Super Fun',
        href='https://www.youtube.com/channel/UCBZiUUYeLfS5rIj4TQvgSvA/videos',
    ),
    feed(
        title='PRIME',
        title_full='PRIME ORCHESTRA',
        href='https://www.youtube.com/channel/UCKenLkyJUXe50dVrQmLrGpw/videos',
        emojis='💎'
    ),
    feed(
        title='UnboxTherapy',
        title_full='Unbox Therapy',
        href='https://www.youtube.com/channel/UCsTcErHg8oDvUnTzoqsYeNw/videos',
    ),
    feed(
        title='Wylsa',
        title_full='Wylsacom',
        href='https://www.youtube.com/channel/UCt7sv-NKh44rHAEb-qCCxvA/videos',
    ),
    feed(
        title='Nigri',
        title_full='Jessica Nigri',
        href='https://www.youtube.com/channel/UCTg4jls4URruaHauposrhMg/videos',
        emojis='🏮💎'
    ),
    feed(
        title='КременюкИ',
        href='https://www.youtube.com/channel/UCgLQh3fGZmfgbJ8D_sry-kA/videos',
        emojis='💎'
    ),
    feed(
        title='Т—Ж',
        title_full='Тинькофф-Журнал (YouTube)',
        href='https://www.youtube.com/channel/UCyYdliihJFWMXHikPK3NCQA/videos',
    ),
    feed(
        title='Cosplay01',
        title_full='bky guy',
        href='https://www.youtube.com/channel/UCF2mFIUwbn6bANVq8xbmjdg/videos',
        emojis='🏮',
    ),
    feed(
        title='Cosplay02',
        title_full='Herzlocast',
        href='https://www.youtube.com/channel/UCOCTIJiEVbSQaXeaScId_cQ/videos',
        emojis='🏮',
    ),
    feed(
        title="Cosplay03",
        title_full="Milligan Vick",
        href="https://www.youtube.com/channel/UCPi1NLlECKm4VGpNjDUiBmg/videos",
        emojis='🏮',
    ),
    feed(
        title='Астамуринг',
        href='https://www.youtube.com/channel/UCwqpU4SDWcRpL9YIuwYtF1A/videos',
    ),
    feed(
        title='Интервьюер',
        title_full='Зе Интервьюер',
        href='https://www.youtube.com/channel/UCuWDlf53jjxti-aUA4tBdsA/videos',
        emojis='💎'
    ),
    feed(
        title='Банкир',
        title_full='Бегущий Банкир',
        href='https://www.youtube.com/channel/UCqVKtuYmKkVPaBeNFWRxlMw/videos',
    ),
    feed(
        title='Навальный',
        title_full='Алексей Навальный',
        href='https://www.youtube.com/channel/UCsAw3WynQJMm7tMy093y37A/videos',
    ),
    feed(
        title='Rapha',
        title_full='Rapha Films',
        href='https://www.youtube.com/channel/UCXYXxfVjxMppZY64-5baOsw/videos',
    ),
    feed(
        title='MarkFood',
        title_full='Mark Wiens - Hungry tourist',
        href='https://www.youtube.com/channel/UCyEd6QBSgat5kkC6svyjudA/videos',
    ),
    feed(
        title='Kaufman',
        title_full='Ron Kaufman',
        href='https://www.youtube.com/channel/UCGczcywiY2efmZ4lYb6jB9Q/videos',
    ),
    feed(
        title='FCade',
        title_full='Francis Cade',
        href='https://www.youtube.com/channel/UCHyBWpfAggsFPDc5A7l_eWA/videos',
    ),
    feed(
        title='Raquel',
        title_full='Raquel Reed',
        href='https://www.youtube.com/channel/UCcSow8gRPkLK0u-1pLMkZsw/videos',
        emojis='🏮💎'
    ),
    feed(
        title='NurkFPV',
        title_full='Nurk FPV',
        href='https://www.youtube.com/channel/UCPCc4i_lIw-fW9oBXh6yTnw/videos',
    ),
    feed(
        title='VergeYT',
        title_full='The Verge (YouTube)',
        href='https://www.youtube.com/channel/UCddiUEpeqJcYeBxX1IVBKvQ/videos',
        emojis='💎'
    ),
    feed(
        title='VergeScienceYT',
        title_full='The Verge Science (YouTube)',
        href='https://www.youtube.com/channel/UCtxJFU9DgUhfr2J2bveCHkQ/videos',
        emojis='💎'
    ),
    feed(
        title='mono',
        title_full='monobank',
        href='https://www.youtube.com/channel/UClF9NLW6p4QZ28rGp8ExbAg/videos',
        emojis='💎'
    ),
    feed(
        title='Yakushev',
        title_full='Andrei Yakushev',
        href='https://www.youtube.com/channel/UCfA7eqgBGvJuBcMS8PDFjcg/videos',
        emojis='💎'
    ),
    feed(
        title="ПланетаКино",
        title_full="Планета Кино",
        href='https://www.youtube.com/channel/UCrR7GJSvz481CxHQn-yXHJw/videos',
        emojis='💎'
    ),
    feed(
        title="MLewin",
        title_full="Michelle Lewin",
        href="https://www.youtube.com/channel/UCXOF8RQ_v52K1uq6m_rMy1w/videos",
        emojis='🏮',
    ),
    feed(
        title="AdventureTeam",
        title_full="Adventure Team",
        href="https://www.youtube.com/channel/UCnusq0cEepVKVAlftFn8u5Q/videos",
        emojis='💎'
    ),
    feed(
        title="OverwatchRU",
        title_full="Overwatch RU",
        href="https://www.youtube.com/channel/UCpW84gDcZu8wNQ-tUO5qE6A/videos",
        emojis='💎'
    ),
    feed(
        title="cherrycrush",
        title_full="My Cherry Crush",
        href="https://www.youtube.com/channel/UC4lkVwG5XViZuoRrjdUqEeA/videos",
        emojis='🏮',
    ),
    feed(
        title="Snazzy",
        title_full="Snazzy Labs",
        href="https://www.youtube.com/channel/UCO2x-p9gg9TLKneXlibGR7w/videos",
        emojis='💎'
    ),
    feed(
        title='Хач',
        title_full='ДНЕВНИК ХАЧА',
        href='https://www.youtube.com/channel/UCnbxcA3kZ_uUYIBHNvxpDQw/videos',
        emojis='💎'
    ),
    feed(
        title='ЧумацкийВелопробег',
        title_full='Чумацкий путь в Америку - велопробег',
        href='https://www.youtube.com/channel/UC4d-CwWxC8i96D9mKAAtnbA/videos',
    ),
    feed(
        title='Шелягина',
        title_full='Наташа Шелягина',
        href='https://www.youtube.com/channel/UC97y3hRp4lfOhAZpuSbYruQ/videos',
    ),
    feed(
        title='GMBN',
        href='https://www.youtube.com/channel/UC_A--fhX5gea0i4UtpD99Gg/videos',
    ),
    feed(
        title='GMBNTech',
        title_full='GMBN Tech',
        href='https://www.youtube.com/channel/UC6juisijUAHcJLt23nk-qOQ/videos',
    ),
    feed(
        title='ArhyBES',
        href='https://www.youtube.com/channel/UCby5ZKyxiSW3dz_Kg5VDU9w/videos',
        emojis='💎'
    ),
    feed(
        title='Blackpack',
        href='https://www.youtube.com/channel/UChXHexCL-d0538NwLClRDJQ/videos',
        emojis='💎'
    ),
    feed(
        title='Сыендук',
        href='https://www.youtube.com/channel/UC-b89a0Fw6pNoP-g-_qLeiw/videos',
        emojis='💎'
    ),
    feed(
        title='Ленинград',
        href='https://www.youtube.com/channel/UCY0C6A3t3RTUN3BB65rWAgQ/videos',
        emojis='💎'
    ),
    feed(
        title='BadComedian',
        href='https://www.youtube.com/channel/UC6cqazSR6CnVMClY0bJI0Lg/videos',
        emojis='💎'
    ),
    feed(
        title='MKBHD',
        title_full='Marques Brownlee',
        href='https://www.youtube.com/channel/UCBJycsmduvYEL83R_U4JriQ/videos',
    ),
    feed(
        title='Corridor',
        title_full='Corridor Digital',
        href='https://www.youtube.com/channel/UCsn6cjffsvyOZCZxvGoJxGg/videos',
        emojis='💎'
    ),
    feed(
        title='KymNonStop',
        href='https://www.youtube.com/channel/UCM6cd0hPii_FJOzZaxqGj7w/videos',
    ),
    feed(
        title='devinsupertramp',
        href='https://www.youtube.com/channel/UCwgURKfUA7e0Z7_qE3TvBFQ/videos',
        emojis='💎'
    ),
    feed(
        title='IFHT',
        title_full='IFHT Films',
        href='https://www.youtube.com/channel/UCTs59UCfP4YLUt6pDR_uLtg/videos',
        emojis='💎'
    ),
    feed(
        title='Relaxation4K',
        title_full='4K Relaxation Channel',
        href='https://www.youtube.com/channel/UCg72Hd6UZAgPBAUZplnmPMQ/videos',
    ),
    feed(
        title='LazySquare',
        title_full='Lazy Square',
        href='https://www.youtube.com/channel/UCZTc2bbF64cj_r0btHgaakw/videos',
        emojis='💎'
    ),
    feed(
        title='Notordinarytravel',
        title_full='Get out from the ordinary travel',
        href='https://www.youtube.com/channel/UCY5X52SAYFz3nejVwvjf9gg/videos',
        emojis='💎'
    ),
    feed(
        title='Gonzossm',
        href='https://www.youtube.com/channel/UCoFEvb-8o_ONb8pFlZkz64g/videos',
        emojis='💎'
    ),
    feed(
        title='Apple',
        href='https://www.youtube.com/channel/UCE_M8A5yxnLfW0KghEeajjw/videos',
        emojis='💎'
    ),
    feed(
        title='Dobryak',
        title_full='Dobryak animations',
        href='https://www.youtube.com/channel/UCIQ1PyEVzV2sc4CXHKH2cSg/videos',
        emojis='💎'
    ),
    feed(
        title='CP',
        title_full='Cycling Pulse',
        href='https://www.youtube.com/channel/UCFtOJh5aZ2hqGA4wJnUEnZw/videos',
    ),
    feed(
        title='Поперечный',
        title_full='Данила Поперечный',
        href='https://www.youtube.com/channel/UCR-Hcwi27-Ee6VnGzmxE1pA/videos',
        emojis='💎'
    ),
    feed(
        title='RVerin',
        title_full='Ruslan Verin — Велопутешествия',
        href='https://www.youtube.com/channel/UCNttYYf1q2RVWkc0Rhulmdw/videos',
        emojis='💎'
    ),
    feed(
        title='HelloFutureMe',
        title_full='Hello Future Me (Storytelling)',
        href='https://www.youtube.com/channel/UCFQMO-YL87u-6Rt8hIVsRjA/videos',
        emojis='💎'
    ),
    feed(
        title='SethHacks',
        title_full="Seth's Bike Hacks",
        href='https://www.youtube.com/channel/UCu8YylsPiu9XfaQC74Hr_Gw/videos',
        emojis='💎'
    ),
    feed(
        title='JYoung',
        title_full='Jonathan Young',
        href='https://www.youtube.com/channel/UC40gs0opj389ohjLnJIAJzA/videos',
        emojis='💎'
    ),
    feed(
        title='Vox',
        href='https://www.youtube.com/channel/UCLXo7UDZvByw2ixzpQCufnA/videos',
        emojis='💎'
    ),
    feed(
        title='Racked',
        href='https://www.youtube.com/channel/UC9HaoyVhTWca7s5QdjY91_A/videos',
        emojis='💎'
    ),
    feed(
        title='MTrawor',
        title_full='Max Trawor',
        href='https://www.youtube.com/channel/UCT4WspI1gXguL9kCOirYBBg/videos',
    ),
    feed(
        title='CGPGrey',
        title_full='CGP Grey',
        href='https://www.youtube.com/channel/UC2C_jShtL725hvbm1arSV9w/videos',
        emojis='💎'
    ),
    feed(
        title='GreatBigStory',
        title_full='Great Big Story',
        href='https://www.youtube.com/channel/UCajXeitgFL-rb5-gXI-aG8Q/videos',
    ),
    feed(
        title='RainfallFilms',
        href='https://www.youtube.com/channel/UCeVw3-4JmOnfx1IsLPywNWg/videos',
        emojis='💎'
    ),
    feed(
        title='AppleSupport',
        title_full='Apple Support',
        href='https://www.youtube.com/channel/UCYFQ33UIPERYx8-ZHucZbDA/videos',
        emojis='💎'
    ),
    feed(
        title='AnimatedSpells',
        title_full='Zee Bashew (animated D&D spells)',
        href='https://www.youtube.com/channel/UCCXR2kCo7Lcw_BKwWxo09kw/videos',
        emojis='💎'
    ),
    feed(
        title='PuffinForrest',
        title_full='Puffin Forrest',
        href='https://www.youtube.com/channel/UCUpkp-6fXuG9dqfoJ99XTmw/videos',
        emojis='💎'
    ),
    feed(
        title='StarfuckedYT',
        title_full='Starfuckedfetish (YouTube)',
        href='https://www.youtube.com/channel/UC7AwpmWErjsVeoZmVWLKxaQ/videos',
        emojis='🏮💎'
    ),
    feed(
        title='LPassion',
        title_full='Latex Passion',
        href='https://www.youtube.com/channel/UC4wJ3VOE_COy2makRex45Sw/videos',
        emojis='🏮💎'
    ),
    feed(
        title='LFashionTV',
        title_full='Latex Fashion TV',
        href='https://www.youtube.com/channel/UCC3iGfxG5wG17GBe1PffP0Q/videos',
        emojis='🏮💎'
    ),
    feed(
        title='Wrapa',
        title_full='Igor Wrapa',
        href='https://www.youtube.com/channel/UC1bsNUFMjbHxiO99GJ8r6mQ/videos',
        emojis='🏮💎'
    ),
    feed(
        title='LRossmann',
        title_full='Louis Rossmann',
        href='https://www.youtube.com/channel/UCl2mFZoRqjw_ELax4Yisf6w/videos',
    ),
    feed(
        title='StanStepanenko',
        href='https://www.youtube.com/channel/UCTMcDOQJgX2ErslaQnKRwKw/videos',
        emojis='💎'
    ),
    feed(
        title='АСтерликов',
        title_full='Александр Стерликов',
        href='https://www.youtube.com/channel/UC89sENALQzDknJNCl-z70Ew/videos',
        emojis='💎'
    ),
    feed(
        title='ROANYERCD',
        title_full='ROANYER CD',
        href='https://www.youtube.com/channel/UCdVmtR_NzLIDoHOBKxahE3A/videos',
        emojis='🏮',
    ),
    feed(
        title='ComradeLtx',
        title_full='comrade latex',
        href='https://www.youtube.com/channel/UCC5-TbHPhx73cqMUMHWMFmw/videos',
        emojis='🏮💎'
    ),
    feed(
        title='JMorrison',
        title_full='Jonathan Morrison',
        href='https://www.youtube.com/channel/UCDlQwv99CovKafGvxyaiNDA/videos',
    ),
    feed(
        title='Specialized',
        title_full='Specialized Bicycles',
        href='https://www.youtube.com/channel/UCcrBtxD8xy2cxeXM7f-xihA/videos',
        emojis='💎🏮'
    ),
    feed(
        title='Scott',
        title_full='SCOTT Sports',
        href='https://www.youtube.com/channel/UCDfnam79n2tXXumz9i7jnIA/videos',
    ),
    feed(
        title='РОрловХа',
        title_full='Роман Орлов (Харьков!)',
        href='https://www.youtube.com/channel/UCqoWNnPA_EJaPxe6BLG8QHA/videos',
        emojis='💎'
    ),
    feed(
        title='Игронавты',
        href='https://www.youtube.com/channel/UCTK88HZEOljUoIZyOrLSM2g/videos',
        emojis='💎'
    ),
    feed(
        title='СтасДавыдов',
        title_full='Стас Давыдов',
        href='https://www.youtube.com/channel/UCPEOh8hH_dNSIhUr4N3y6ng/videos',
        emojis='💎'
    ),
    feed(
        title='ShoShoser',
        href='https://www.youtube.com/channel/UCFeRx6XCRVLaVVQgr0ZQhlQ/videos',
        emojis='💎'
    ),
    feed(
        title='PrimeBike',
        title_full='Prime Bike',
        href='https://www.youtube.com/channel/UCOczCghYGW019XHlJ-0stxw/videos',
    ),
    feed(
        title='Гуфовский',
        href='https://www.youtube.com/channel/UCRT9pHOR2iY4qw0qxt7dQpw/videos',
        emojis='💎'
    ),
    feed(
        title='Mbike',
        href='https://www.youtube.com/channel/UCrJB33zyMCYYOQeYfN8bs5w/videos',
        emojis='💎'
    ),
    feed(
        title='ГАРАЖ',
        href='https://www.youtube.com/channel/UCa2l2SX7VnV3XSfS2Qe951Q/videos',
        emojis='💎'
    ),
    feed(
        title='LoL',
        title_full='League of Legends',
        href='https://www.youtube.com/channel/UC2t5bjwHdUX4vM2g8TRDq5g/videos',
        emojis='💎'
    ),
    feed(
        title='ПроПутешествия',
        title_full='ПРО ПУТЕШЕСТВИЯ Богдан Булычёв',
        href='https://www.youtube.com/channel/UCgovv1nO7nnCwulSBa2Kjsw/videos',
    ),
    feed(
        title='Ancord',
        title_full='ANCORD - Русский Голос Аниме',
        href='https://www.youtube.com/channel/UC40zik1zj7yE8oqOYBxAS3A/videos',
    ),
    feed(
        title='AniZor',
        href='https://www.youtube.com/channel/UCeW38CoW54j1GgTrer5JQLg/videos',
        emojis='💎'
    ),
    feed(
        title='DimitryB',
        title_full='Dimitry B',
        href='https://www.youtube.com/channel/UCOQXxrZprZMHsg6zC-uQcGw/videos',
    ),
    feed(
        title='ЧудоТехники',
        title_full='Чудо техники',
        href='https://www.youtube.com/channel/UCRP4EhX1Op-jL7D87PB3qhQ/videos',
    ),
    feed(
        title='Halocene',
        href='https://www.youtube.com/channel/UCoimajyGy33X_Pqt-SHCWeA/videos',
        emojis='💎'
    ),
    feed(
        title='BABYMETAL',
        href='https://www.youtube.com/channel/UC33_tIj4m1_XaqfFcomShvw/videos',
        emojis='💎'
    ),
    feed(
        title='WylsaLive',
        href='https://www.youtube.com/channel/UCAfkLSa-ujPKhniiKZ2bCHg/videos',
        emojis='💎'
    ),
    feed(
        title='DUST',
        href='https://www.youtube.com/channel/UC7sDT8jZ76VLV1u__krUutA/videos',
        emojis='💎'
    ),
    feed(
        title='ThisIs',  # by Linus
        title_full='This Is',
        href='https://www.youtube.com/channel/UC1IQIspOkCeV3WnYm32SBFQ/videos',
        emojis='💎'
    ),
    feed(
        title='VolFMaple',
        href='https://www.youtube.com/channel/UC7O7af501mv4Ab4oCSdPTxw/videos',
        emojis='💎'
    ),
    feed(
        title='ШамовДмитрий',
        title_full='Шамов Дмитрий: жизнь в Японии',
        href='https://www.youtube.com/channel/UCDNXL3G7Mz594L1CVFp3CMQ/videos',
    ),
    feed(
        title='varlamov',
        href='https://www.youtube.com/channel/UC101o-vQ2iOj9vr00JUlyKw/videos',
    ),
    feed(
        title='DheroesC',
        title_full='DheroesC: рассказы из комиксов',
        href='https://www.youtube.com/channel/UCp8tldEJKFDS1dM5eOk0Clg/videos',
        emojis='💎'
    ),
    feed(
        title='MyLatexBaby',
        href='https://www.youtube.com/channel/UCvxaNRCpQPI-3OVLDt7ywOQ/videos',
        emojis='💎'
    ),
    feed(
        title='Зеленский',
        href='https://www.youtube.com/channel/UCp2zBKrqP0ZQF6RN4RJtF2Q/videos',
        emojis='💎'
    ),
    feed(
        title='Anidub',
        title_full='Anidub Online',
        href='feed:https://online.anidub.com/rss.xml',
        href_title='feed:https://online.anidub.com/rss.xml',
        emojis='💎'
    ),
    feed(
        title='AnimeVost',
        href='http://animevost.org/rss.xml',
        href_title='http://animevost.org',
        emojis='💎'
    ),
    feed(
        title='Gam3',
        title_full='The Gam3',
        href='feed:https://thegam3.com/feed/',
        href_title='https://thegam3.com',
        emojis='💎'
    ),
    feed(
        title='Jago',
        title_full='Jagodibuja',
        href='feed://www.jagodibuja.com/feed/',
        href_title='http://www.jagodibuja.com',
        emojis='💎'
    ),
    feed(
        title='vas3k',
        title_full='vas3k.ru',
        href='feed:https://vas3k.ru/rss/',
        href_title='https://vas3k.ru/',
        emojis='💎'
    ),
    feed(
        title='DisgustingMen',
        title_full='Disgusting Men',
        href='feed:https://disgustingmen.com/feed/',
        href_title='https://disgustingmen.com/',
        emojis='💎'
    ),
    feed(
        title='XKCD',
        href='https://xkcd.com/rss.xml',
        href_title='https://xkcd.com',
        emojis='💎',
        delay=18
    ),
    feed(
        title='ReflectiveDesire',
        title_full='Reflective Desire',
        href='http://reflectivedesire.com/rss/',
        href_title='http://reflectivedesire.com/',
        emojis='🏮💎'
    ),
    feed(
        title='Verge',
        title_full='The Verge',
        href='https://www.theverge.com/rss/index.xml',
        href_title='https://www.theverge.com/',
    ),
    feed(
        title='КабМин',
        title_full='Кабинет Министров Украины',
        href='https://www.kmu.gov.ua/api/rss',
        href_title='https://www.kmu.gov.ua/',
    ),
    feed(
        title='Shadman',
        title_full='Shadbase by Shadman',
        href='feed://www.shadbase.com/feed/',
        href_title='http://www.shadbase.com/',
        emojis='🏮💎',
        delay=42
    ),
    feed(
        title='FisheyePlacebo',
        title_full='Fisheye Placebo',
        href='feed://readmanga.me/rss/manga?name=fisheye_placebo',
        href_title='http://readmanga.me/fisheye_placebo',
        emojis='💎'
    ),
    feed(
        title='OnePunchMan',
        title_full='One Punch Man',
        href='feed://readmanga.me/rss/manga?name=one_punch_man',
        href_title='http://readmanga.me/one_punch_man__A1be6f8',
        emojis='💎'
    ),
    feed(
        title='Пик',
        title_full='Пик боевых искусств',
        href='feed://readmanga.me/rss/manga?name=martial_peak',
        href_title='http://readmanga.me/martial_peak',
        emojis='💎'
    ),
    feed(
        title='ТронБога',
        title_full='Трон, отмеченный Богом',
        href='feed://readmanga.me/rss/manga?name=sealed_divine_throne',
        href_title='http://readmanga.me/sealed_divine_throne',
        emojis='💎'
    ),
    feed(
        title='FairyTail100',
        title_full='Fairy Tail: 100 Years Quest',
        href='feed://readmanga.me/rss/manga?name=fairy_tail__100_years_quest',
        href_title='http://readmanga.me/fairy_tail__100_years_quest',
        emojis='💎'
    ),
    feed(
        title='ГеройКопья',
        title_full='Перерождение героя копья',
        href='feed://readmanga.me/rss/manga?name=redo_of_the_spear_hero',
        href_title='http://readmanga.me/redo_of_the_spear_hero',
        emojis='💎'
    ),
    feed(
        title='ZoneTan',
        title_full='Приключения Zone-Tan',
        href='feed://readmanga.me/rss/manga?name=zone_tan_adventures',
        href_title='http://readmanga.me/zone_tan_adventures',
        emojis='💎'
    ),
    feed(
        title='ЧеловеческиеКарты',
        title_full='Человеческие карты',
        href='feed://readmanga.me/rss/manga?name=human_card',
        href_title='http://readmanga.me/human_card',
        emojis='💎'
    ),
    feed(
        title='БольшеНеГерой',
        title_full='Герой? Я давно перестал им быть',
        href='feed://readmanga.me/rss/manga?name=hero__i_quit_a_long_time_ago',
        href_title='http://readmanga.me/hero__i_quit_a_long_time_ago',
        emojis='💎'
    ),
    feed(
        title='Эликсир',
        title_full='Исцеляющий эликсир',
        href='feed://readmanga.me/rss/manga?name=healing_elixir',
        href_title='http://readmanga.me/healing_elixir',
        emojis='💎'
    ),
    feed(
        title='Начало',
        title_full='Начало после конца',
        href='feed://readmanga.me/rss/manga?name=nachalo_posle_konca',
        href_title='http://readmanga.me/nachalo_posle_konca',
        emojis='💎'
    ),
    feed(
        title='DuskHowler',
        title_full='Dusk Howler',
        href='feed://readmanga.me/rss/manga?name=dusk_howler',
        href_title='http://readmanga.me/dusk_howler',
        emojis='💎'
    ),
    feed(
        title='FirePlay',
        title_full='C огнём играешь, Юйвэнь Цзюнь!',
        href='http://readmanga.me/c_ognem_igraesh__iuiven_cziun_',
        emojis='💎'
    ),
    feed(
        title='ОсобеннаяМагия',
        title_full='Магия вернувшегося должна быть особенной',
        href='feed://readmanga.me/rss/manga?name=magiia_vernuvshegosia_doljna_byt_osobennoi',
        href_title='http://readmanga.me/magiia_vernuvshegosia_doljna_byt_osobennoi',
        emojis='💎'
    ),
    feed(
        title='КоролеваОперы',
        title_full='Королева оперы',
        href='feed://readmanga.me/rss/manga?name=the_queen_of_the_opera',
        href_title='http://readmanga.me/the_queen_of_the_opera',
        emojis='💎'
    ),
    feed(
        title='ЗимаЛето',
        title_full='Зима подходит к Лету',
        href='feed://readmanga.me/rss/manga?name=zima_podhodit_k_letu',
        href_title='http://readmanga.me/zima_podhodit_k_letu',
        emojis='💎'
    ),
    feed(
        title='ЖаждаМагии',
        title_full='Бывший сильнейший мечник жаждет магии в другом мире',
        href='feed://readmanga.me/rss/manga?name=ex_strongest_swordsman_long_for_magic_in_different_world',
        href_title='http://readmanga.me/ex_strongest_swordsman_long_for_magic_in_different_world',
        emojis='💎'
    ),
    feed(
        title='Заступник',
        title_full='Самый сильный в мире Заступник',
        href='feed://readmanga.me/rss/manga?name=world_strongest_rearguard___labyrinth_country_and_dungeon_seekers',
        href_title='http://readmanga.me/world_strongest_rearguard___labyrinth_country_and_dungeon_seekers',
        emojis='💎'
    ),
    feed(
        title='Ветролом',
        href='feed://readmanga.me/rss/manga?name=wind_breaker',
        href_title='http://readmanga.me/wind_breaker',
        emojis='💎'
    ),
    feed(
        title='БурныйВек',
        title_full='Бурный век',
        href='feed://readmanga.me/rss/manga?name=volcanic_age',
        href_title='http://readmanga.me/volcanic_age',
        emojis='💎'
    ),
    feed(  # окончено автором, продолжения не планируется (кроме книги?)
        title='БессмертныйТорговец',
        title_full='Бессмертный торговец',
        href='feed://readmanga.me/rss/manga?name=immortal_merchant',
        href_title='http://readmanga.me/immortal_merchant',
    ),
    feed(
        title='ВеликийМеч',
        title_full='Мой великий меч',
        href='feed://readmanga.me/rss/manga?name=moi_velikii_mech',
        href_title='http://readmanga.me/moi_velikii_mech',
        emojis='💎'
    ),
    feed(
        title='SoloLeveling',
        title_full='Поднятие уровня в одиночку',
        href='feed://readmanga.me/rss/manga?name=podniatie_urovnia_v_odinochku',
        href_title='http://readmanga.me/podniatie_urovnia_v_odinochku',
        emojis='💎'
    ),
    feed(
        title='МолчаливаяЛуна',
        title_full='Молчаливая луна',
        href='feed://readmanga.me/rss/manga?name=yue_chen_yin',
        href_title='http://readmanga.me/yue_chen_yin',
        emojis='💎'
    ),
    feed(
        title='Вовсеоружии',
        title_full='Во всеоружии',
        href='feed://readmanga.me/rss/manga?name=vo_vseorujii',
        href_title='http://readmanga.me/vo_vseorujii',
        emojis='💎'
    ),
    feed(
        title='ЧерныйПризыватель',
        title_full='Чёрный Призыватель',
        href='feed://readmanga.me/rss/manga?name=black_summoner',
        href_title='http://readmanga.me/black_summoner',
        emojis='💎'
    ),
    feed(
        title='ЧерныйДьявол',
        title_full='Черный Дьявол',
        href='feed://readmanga.me/rss/manga?name=chernyi_diavol',
        href_title='http://readmanga.me/chernyi_diavol',
        emojis='💎'
    ),
    feed(
        title='НикудышныеПринцессы',
        title_full='Никудышные принцессы',
        href='feed://readmanga.me/rss/manga?name=useless_princesses',
        href_title='http://readmanga.me/useless_princesses',
        emojis='💎'
    ),
    feed(
        title='ЖенщинаРыцарь',
        title_full='История о том, как обращаться с женщиной-рыцарем, к которой никогда не относились как к женщине',
        href='feed://readmanga.me/rss/manga?name=a_story_about_treating_a_female_knight_who_has_never_been_treated_as_a_woman',
        href_title='http://readmanga.me/a_story_about_treating_a_female_knight_who_has_never_been_treated_as_a_woman',
        emojis='💎'
    ),
    feed(
        title='ГородскиеФеи',
        title_full='Хвост феи: Городской герой',
        href='feed://readmanga.me/rss/manga?name=hvost_fei__gorodskoi_geroi',
        href_title='http://readmanga.me/hvost_fei__gorodskoi_geroi',
        emojis='💎'
    ),
    feed(
        title='ЧитРоста',
        title_full='Я могу делать всё со своим Читом Роста, но я всё равно останусь безработным',
        href='feed://readmanga.me/rss/manga?name=i_ve_became_able_to_do_anything_with_my_growth_cheat__but_i_can_t_seem_to_get_out_of_being_jobless__novel_',
        href_title='http://readmanga.me/i_ve_became_able_to_do_anything_with_my_growth_cheat__but_i_can_t_seem_to_get_out_of_being_jobless__novel_',
        emojis='💎'
    ),
    feed(
        title='ЯМоб',
        title_full='Я моб',
        href='feed://readmanga.me/rss/manga?name=i_am_mob',
        href_title='http://readmanga.me/i_am_mob',
        emojis='💎'
    ),
    feed(
        title='ГорожанинКультиватор',
        title_full='Перерождение бессмертного горожанина-культиватора',
        href='feed://readmanga.me/rss/manga?name=pererojdenie_bessmertnogo_gorojanina_kultivatora',
        href_title='http://readmanga.me/pererojdenie_bessmertnogo_gorojanina_kultivatora',
        emojis='💎'
    ),
    feed(
        title='Варбл',
        href='feed://readmanga.me/rss/manga?name=varbl',
        href_title='http://readmanga.me/varbl',
        emojis='💎'
    ),
    feed(
        title='яNPC',
        title_full='Я притворяюсь NPC',
        href='feed://readmanga.me/rss/manga?name=ia_pritvoriaius_npc',
        href_title='http://readmanga.me/ia_pritvoriaius_npc',
        emojis='💎'
    ),
    feed(
        title='ДраконийОхотник',
        title_full='Охотник на драконов',
        href='feed://readmanga.me/rss/manga?name=dragon_hunter',
        href_title='http://readmanga.me/dragon_hunter',
        emojis='💎'
    ),
    feed(
        title='ДвеДуши',
        href='feed://readmanga.me/rss/manga?name=two_souls',
        href_title='http://readmanga.me/two_souls',
        emojis='💎'
    ),
    feed(
        title='Персона5',
        title_full='Персона 5: Антология мини-историй',
        href='feed://readmanga.me/rss/manga?name=persona_5__antologiia_mini_istorii',
        href_title='http://readmanga.me/persona_5__antologiia_mini_istorii',
        emojis='💎'
    ),
    feed(
        title='Франкс',
        title_full='Милый во Франксе! Ёнкома',
        href='http://readmanga.me/darling_in_the_franxx___4_koma_',
        emojis='💎'
    ),
    feed(
        title='JoshuaWright',
        title_full='Joshua Wright (SlackWyrm)',
        href='feed://www.joshuawright.net/rss_joshuawright.xml',
        href_title='http://www.joshuawright.net/index.html',
        emojis='💎',
    ),
    feed(
        title='DTF',
        title_full='DTF (Everything new)',
        href='https://dtf.ru/rss/new',
        href_title='https://dtf.ru/top/month',
    ),
    feed(
        title='Т—Журнал',
        title_full='Тинькофф-Журнал',
        href='feed:https://journal.tinkoff.ru/feed/',
        href_title='https://journal.tinkoff.ru',
    ),
    feed(
        title='octokuro',
        title_full='OCTOKURO',
        href='feed:https://www.octokuro.com/gallery?format=feed&type=rss',
        href_title='feed:https://www.octokuro.com/gallery',
        emojis='🏮💎',
    ),
    feed(
        title='oglaf',
        title_full='oglaf.com',
        href='feed:https://www.oglaf.com/feeds/rss/',
        href_title='https://www.oglaf.com',
        emojis='🏮💎',
        delay=24
    ),
    feed(
        title='mortalezz',
        title_full='Gorsky (@mortalezz)',
        href='feed:https://gorsky.us/rss/',
        href_title='https://gorsky.us/',
        emojis='💎',
    ),
    feed(
        title='CommitStrip',
        title_full='Commit Strip',
        href='feed://www.commitstrip.com/en/feed/',
        href_title='http://www.commitstrip.com/en/',
        emojis='💎',
    ),
    feed(
        title='Tonsky',
        title_full='Tonsky',
        href='http://tonsky.me/blog/atom.xml',
        href_title='http://tonsky.me',
        emojis='💎',
    ),
    feed(
        title='bespoyasov',
        title_full='bespoyasov',
        href='https://bespoyasov.ru/rss.xml',
        href_title='https://bespoyasov.ru',
        emojis='💎',
    ),
    feed(
        title='Wren',
        title_full='DarkWren',
        href='https://darkwren.ru/feed/',
        href_title='https://darkwren.ru/',
    ),
    feed(
        title='IDEA',
        title_full='IDEA Instructions',
        href='https://idea-instructions.com/feed.xml',
        href_title='https://idea-instructions.com',
        emojis='💎',
    ),
    feed(
        title='erotibotica',
        href='https://erotibotica.com/feed/',
        href_title='https://erotibotica.com',
        emojis='💎',
    ),
    feed(
        title='Шелдон',
        title_full='Детство Шелдона',
        href='https://kuraj-serials.ru/rss.xml',
        href_title='https://куражбамбей.рф/serial-detstvo-sheldona-2-sezon-9-seriya.html',
        emojis='💎',
        filter='serial-detstvo-sheldona'
    ),
    feed(
        title='Keddr',
        title_full='Keddr.com',
        href='feed:https://keddr.com/feed/',
        href_title='https://keddr.com/',
    ),
    feed(
        title='Щит',
        title_full='Становление Героя Щита',
        href='https://ruranobe.ru/updates.rss',
        href_title='https://ruranobe.ru/r/tnynn',
        filter='ruranobe.ru/r/tnynn/'
    ),
    feed(
        title='AW',
        title_full='Accel World',
        href='https://ruranobe.ru/updates.rss',
        href_title='https://ruranobe.ru/r/aw',
        filter='ruranobe.ru/r/aw/',
        emojis='💎',
    ),
    feed(
        title='ЭльфийскаяКровь',
        title_full='Эльфийская кровь',
        href='https://ruranobe.ru/updates.rss',
        href_title='https://ruranobe.ru/r/sne',
        filter='ruranobe.ru/r/sne/',
        emojis='💎',
    ),
    feed(
        title='ЗвездныйГерб',
        title_full='Звездный герб',
        href='https://ruranobe.ru/updates.rss',
        href_title='https://ruranobe.ru/r/snm',
        filter='ruranobe.ru/r/snm/',
        emojis='💎',
    ),
    feed(
        title='SAOrura',
        title_full='Sword Art Online (ruranobe.ru)',
        href='https://ruranobe.ru/updates.rss',
        href_title='https://ruranobe.ru/r/sao',
        filter='ruranobe.ru/r/sao/',
        emojis='💎',
    ),
    feed(
        title='NieR',
        title_full='NieR:Automata',
        href='https://works.novel.tl/updates.rss',
        href_title='https://works.novel.tl/r/nier',
        filter='works.novel.tl/r/nier/',
        emojis='💎',
    ),
    feed(
        title='SkazOff',
        title_full='SkazOff Blog',
        href='feed:https://skazoff.ru/feed/',
        href_title='https://skazoff.ru',
        emojis='💎',
    ),
    feed(
        title='WaitButWhy',
        title_full='Wait But Why',
        href='https://waitbutwhy.com/feed',
        href_title='https://waitbutwhy.com',
        emojis='💎',
    ),
    feed(
        title='Озорнин',
        title_full='Блог Михаила Озорнина',
        href='feed://mikeozornin.ru/blog/rss/',
        href_title='http://mikeozornin.ru/blog/',
        emojis='💎',
    ),
    feed(
        title='CSStricks',
        title_full='CSS-Tricks',
        href='feed:https://css-tricks.com/feed/',
        href_title='https://css-tricks.com',
        emojis='💎',
    ),
    feed(
        title='ХТ',
        title_full='Харьков-Турист',
        href='feed://xt.ht/rss.php',
        href_title='http://xt.ht',
        emojis='💎',
    ),
    feed(  # https://telegram2rss.akin.su/site/ru/
        title='Expresso',
        href='feed:https://telegram2rss.akin.su/api/channel/feed/expressotoday/9FE04EFAC787',
        href_title='https://t.me/expressotoday',
        emojis='💎',
    ),
    feed(
        title='MyInstagram',
        href='https://www.instagram.com/olehkrupko/',
        emojis='👤'
    ),
    feed(
        title='MyStrava',
        href='http://feedmyride.net/activities/21952815',
        href_title='https://www.strava.com/athlete/training',
        emojis='👤'
    ),
    feed(
        title='HomepageGithub',
        href='https://github.com/olehkrupko/Homepage/commits/master.atom',
        href_title='https://github.com/olehkrupko/Homepage',
        emojis='👤'
    ),
    feed(
        title='LeniviyART',
        href='https://twitrss.me/twitter_user_to_rss/?user=leniviy_art',
        href_title='https://leniviyart.com/illustration',
        emojis='💎🏮'
    ),
    feed(
        title='kalinkafox',
        href='https://twitrss.me/twitter_user_to_rss/?user=kalinkafox',
        href_title='https://twitter.com/kalinkafox',
        emojis='💎🏮'
    ),
    feed(
        title='OJessicaNigri',
        href='https://twitrss.me/twitter_user_to_rss/?user=OJessicaNigri',
        href_title='https://twitter.com/OJessicaNigri',
        emojis='💎🏮'
    ),
    feed(
        title='InCaseArt',
        href='https://twitrss.me/twitter_user_to_rss/?user=InCaseArt',
        href_title='https://twitter.com/InCaseArt',
        emojis='💎🏮'
    ),
    feed(
        title='StvartakMato',
        href='https://twitrss.me/twitter_user_to_rss/?user=StvartakMato',
        href_title='https://twitter.com/StvartakMato',
        emojis='💎🏮'
    ),
    feed(
        title='bangbez',
        href='feed:https://bangbez.artstation.com/rss',
        href_title='https://bangbez.artstation.com/projects',
        emojis='💎🏮'
    ),
    feed(
        title='tudvaseva',
        href='feed:https://tudvaseva.artstation.com/rss',
        href_title='https://tudvaseva.artstation.com/projects',
        emojis='💎🏮'
    ),
    feed(
        title='Starf',
        title_full='Starfucked model',
        href='https://twitrss.me/twitter_user_to_rss/?user=StarfuckedModel',
        href_title='https://twitter.com/StarfuckedModel',
        emojis='💎🏮'
    ),
    feed(
        title='Zeronis',
        href='feed:https://www.artstation.com/zeronis-pk.rss',
        href_title='https://www.artstation.com/zeronis-pk',
        emojis='💎🏮'
    ),
    feed(
        title='DominikDraw',
        href='feed:https://www.artstation.com/dominikdraw.rss',
        href_title='https://www.artstation.com/dominikdraw',
        emojis='💎🏮'
    ),
    feed(
        title='TonySkeor',
        href='feed:https://www.artstation.com/skeor.rss',
        href_title='https://www.artstation.com/skeor',
        emojis='💎🏮'
    ),
    feed(
        title='WojciechWilk',
        href='feed:https://www.artstation.com/wojciechwilk.rss',
        href_title='https://www.artstation.com/wojciechwilk',
        emojis='💎🏮'
    ),
    feed(
        title='SashaTudvaseva',
        href='feed:https://www.artstation.com/tudvaseva.rss',
        href_title='https://www.artstation.com/tudvaseva',
        emojis='💎🏮'
    ),
    feed(
        title='JannetWeb',
        title_full='Jannet Incosplay Website',
        href='feed:https://jannetincosplay.com/recent.rss',
        href_title='https://jannetincosplay.com',
        emojis='💎🏮'
    ),
    feed(
        title='JannetTwi',
        title_full='Jannet Incosplay Twitter',
        href='feed:https://twitrss.me/twitter_user_to_rss/?user=in_cosplay',
        href_title='https://twitter.com/in_cosplay',
        emojis='💎🏮'
    ),
    feed(
        title='JannetDevArt',
        title_full='Jannet Incosplay Deviantart',
        href='http://backend.deviantart.com/rss.xml?q=gallery%3Ajannet-sorekage',
        href_title='https://www.deviantart.com/jannet-sorekage/gallery/',
        emojis='💎🏮'
    ),
    feed(
        title='JannetYT',
        title_full='Jannet Incosplay YouTube',
        href='https://www.youtube.com/channel/UCr2dfQlDaZlqpAPv_TKYSdQ/videos',
        emojis='💎🏮'
    ),
    feed(
        title='KalinkaFoxTumblr',
        href='https://kalinkafox.tumblr.com/rss',
        href_title='https://kalinkafox.tumblr.com',
        emojis='💎🏮'
    ),
    feed(
        title='cherrymousestreet',
        href='https://cherrymousestreet.tumblr.com/rss',
        href_title='https://cherrymousestreet.tumblr.com',
        emojis='💎🏮'
    ),
    feed(
        title='saiwsaiwsaiw',
        href='feed:https://twitrss.me/twitter_user_to_rss/?user=saiwsaiwsaiw',
        href_title='https://twitter.com/saiwsaiwsaiw',
        emojis='💎🏮'
    ),
    feed(
        title='buttsmithy',
        href='https://buttsmithy.com/feed',
        href_title='https://buttsmithy.com',
        emojis='💎🏮'
    ),
    feed(
        title='octokuroTwi',
        title_full='octokuro_model Twitter',
        href='feed:https://twitrss.me/twitter_user_to_rss/?user=octokuro_model',
        href_title='https://twitter.com/octokuro_model',
        emojis='💎🏮'
    ),
    feed(
        title='SambucaTwi',
        title_full='Sambuca Twitter',
        href='feed:https://twitrss.me/twitter_user_to_rss/?user=officialsambuca',
        href_title='https://twitter.com/officialsambuca',
        emojis='💎🏮'
    ),
    feed(
        title='cherrygig',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/cherry-gig',
        href_title='http://www.hentai-foundry.com/pictures/user/cherry-gig',
        emojis='💎🏮'
    ),
    feed(
        title='OwlerHF',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/Owler',
        href_title='http://www.hentai-foundry.com/pictures/user/Owler',
        emojis='💎🏮'
    ),
    feed(
        title='foxicube',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/foxicube',
        href_title='http://www.hentai-foundry.com/pictures/user/foxicube',
        emojis='💎🏮'
    ),
    feed(
        title='Cutesexyrobutts',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/Cutesexyrobutts',
        href_title='http://www.hentai-foundry.com/pictures/user/Cutesexyrobutts',
        emojis='💎🏮'
    ),
    feed(
        title='NobuOne',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/NobuONE',
        href_title='http://www.hentai-foundry.com/pictures/user/NobuONE',
        emojis='💎🏮'
    ),
    feed(
        title='Cicada',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/Cicada',
        href_title='http://www.hentai-foundry.com/pictures/user/Cicada',
        emojis='💎🏮'
    ),
    feed(
        title='DevilHS',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/DevilHS',
        href_title='http://www.hentai-foundry.com/pictures/user/DevilHS',
        emojis='💎🏮'
    ),
    feed(
        title='LeraPi',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/LeraPI',
        href_title='http://www.hentai-foundry.com/pictures/user/LeraPI',
        emojis='💎🏮'
    ),
    feed(
        title='DominikDrawHF',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/DominikDraw',
        href_title='http://www.hentai-foundry.com/pictures/user/DominikDraw',
        emojis='💎🏮'
    ),
    feed(
        title='DeviantHunter',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/DeviantHunter',
        href_title='http://www.hentai-foundry.com/pictures/user/DeviantHunter',
        emojis='💎🏮'
    ),
    feed(
        title='kajinman',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/kajinman',
        href_title='http://www.hentai-foundry.com/pictures/user/kajinman',
        emojis='💎🏮'
    ),
    feed(
        title='kokobuttz',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/kokobuttz',
        href_title='http://www.hentai-foundry.com/pictures/user/kokobuttz',
        emojis='💎🏮'
    ),
    feed(
        title='BadCompz',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/BADCOMPZ',
        href_title='http://www.hentai-foundry.com/pictures/user/BADCOMPZ',
        emojis='💎🏮'
    ),
    feed(
        title='FlowerxlHF',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/Flowerxl',
        href_title='http://www.hentai-foundry.com/pictures/user/Flowerxl',
        emojis='💎🏮'
    ),
    feed(
        title='aromasensei',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/aromasensei',
        href_title='http://www.hentai-foundry.com/pictures/user/aromasensei',
        emojis='💎🏮'
    ),
    feed(
        title='boobsgames',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/boobsgames',
        href_title='http://www.hentai-foundry.com/pictures/user/boobsgames',
        emojis='💎🏮'
    ),
    feed(
        title='tesomu',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/tesomu',
        href_title='http://www.hentai-foundry.com/pictures/user/tesomu',
        emojis='💎🏮'
    ),
    feed(
        title='markydaysaid',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/markydaysaid',
        href_title='http://www.hentai-foundry.com/pictures/user/markydaysaid',
        emojis='💎🏮'
    ),
    feed(
        title='Jummy',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/Jummy',
        href_title='http://www.hentai-foundry.com/pictures/user/Jummy',
        emojis='💎🏮'
    ),
    feed(
        title='Gerph',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/Gerph',
        href_title='http://www.hentai-foundry.com/pictures/user/Gerph',
        emojis='💎🏮'
    ),
    feed(
        title='Skndo',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/Skndo',
        href_title='http://www.hentai-foundry.com/pictures/user/Skndo',
        emojis='💎🏮'
    ),
    feed(
        title='HighBear',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/High-Bear',
        href_title='http://www.hentai-foundry.com/pictures/user/High-Bear',
        emojis='💎🏮'
    ),
    feed(
        title='ebluberry',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/ebluberry',
        href_title='http://www.hentai-foundry.com/pictures/user/ebluberry',
        emojis='💎🏮'
    ),
    feed(
        title='Zillionaire',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/Zillionaire',
        href_title='http://www.hentai-foundry.com/pictures/user/Zillionaire',
        emojis='💎🏮'
    ),
    feed(
        title='ThirtyHelens',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/ThirtyHelens',
        href_title='http://www.hentai-foundry.com/pictures/user/ThirtyHelens',
        emojis='💎🏮'
    ),
    feed(
        title='Owler',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/Owler',
        href_title='http://www.hentai-foundry.com/pictures/user/Owler',
        emojis='💎🏮'
    ),
    feed(
        title='sexgazer',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/sexgazer',
        href_title='http://www.hentai-foundry.com/pictures/user/sexgazer',
        emojis='💎🏮'
    ),
    feed(
        title='AngelWitch',
        href='feed:https://www.hentai-foundry.com/feed/userPictures/username/Angel-Witch',
        href_title='http://www.hentai-foundry.com/pictures/user/Angel-Witch',
        emojis='💎🏮'
    ),
    feed(
        title='KogotsuchiDark',
        href='https://pikabu.ru/@KogotsuchiDark',
        emojis='💎',
    ),
    feed(
        title='Brahmanden',
        title_full='Brahmanden: из Одессы с морковью',
        href='https://pikabu.ru/@Brahmanden',
        emojis='💎',
    ),
    feed(
        title='Мифы',
        title_full='Мифы как мемы',
        href='https://pikabu.ru/@castiar',
        emojis='💎',
    ),
    feed(
        title='LittleBit',
        title_full='Little.Bit',
        href='https://pikabu.ru/@Little.Bit',
        emojis='💎',
    ),
    feed(
        title='Hibren',
        href='https://www.deviantart.com/hibren/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='RalDu',
        href='https://www.deviantart.com/raldu/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='AngeliccMadness',
        href='https://www.deviantart.com/angeliccmadness/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='Cobatsart',
        href='https://www.deviantart.com/cobatsart/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='grimphantom',
        href='https://www.deviantart.com/grimphantom/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='TaNa',
        href='https://www.deviantart.com/ta-na/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='KannelArt',
        href='https://www.deviantart.com/kannelart/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='Reiq',
        href='https://www.deviantart.com/reiq/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='LordDominik',
        href='https://www.deviantart.com/lord-dominik/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='TRYLSC',
        href='https://www.deviantart.com/trylsc/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='CutesexyrobuttsDA',
        href='https://www.deviantart.com/cutesexyrobutts/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='Prywinko',
        href='https://www.deviantart.com/prywinko/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='SatsuiNoHado',
        href='https://www.deviantart.com/satsuinohado/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='Teban1983',
        href='https://www.deviantart.com/teban1983/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='tomaytoTOMAHTO',
        href='https://www.deviantart.com/tomaytotomahto/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='DigitalVox',
        href='https://www.deviantart.com/digital-vox/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='kevinTUT',
        href='https://www.deviantart.com/kevintut/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='Ange1Witch',
        href='https://www.deviantart.com/ange1witch/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='umigraphics',
        href='https://www.deviantart.com/umigraphics/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='glencanlas',
        href='https://www.deviantart.com/glencanlas/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='parapatter',
        href='https://www.deviantart.com/parapatter/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='Sieyarelow',
        href='https://www.deviantart.com/sieyarelow/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='OlchaS',
        href='https://www.deviantart.com/olchas/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='KofJP',
        href='https://www.deviantart.com/kofjp/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='Kyoffie12',
        href='https://www.deviantart.com/kyoffie12/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='logancure',
        href='https://www.deviantart.com/logancure/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='SolKorra',
        href='https://www.deviantart.com/solkorra/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='davidpan',
        href='https://www.deviantart.com/davidpan/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='ganassa',
        href='https://www.deviantart.com/ganassa/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='gtunver',
        href='https://www.deviantart.com/gtunver/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='DarkerEve',
        href='https://www.deviantart.com/darkereve/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='hmongt',
        href='https://www.deviantart.com/hmongt/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='upshdragoon',
        href='https://www.deviantart.com/upshdragoon/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='mleth',
        href='https://www.deviantart.com/mleth/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='MonoriRogue',
        href='https://www.deviantart.com/monorirogue/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='sinceillust',
        href='https://www.deviantart.com/sinceillust/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='ozma02',
        href='https://www.deviantart.com/ozma02/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='velladonna',
        href='https://www.deviantart.com/velladonna/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='Valkymie',
        href='https://www.deviantart.com/valkymie/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='AyyaSAP',
        href='https://www.deviantart.com/ayyasap/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='Nefrubi',
        href='https://www.deviantart.com/nefrubi/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='SplashBrush',
        href='https://www.deviantart.com/splashbrush/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='ROIDESRATS',
        href='https://www.deviantart.com/roidesrats/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='musgravehall',
        href='https://www.deviantart.com/musgravehall/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='Puekkers',
        href='https://www.deviantart.com/puekkers/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='pychopat2',
        href='https://www.deviantart.com/pychopat2/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='rossdraws',
        href='https://www.deviantart.com/rossdraws/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='sakimichan',
        href='https://www.deviantart.com/sakimichan/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='BADCOMPZERO',
        href='https://www.deviantart.com/badcompzero/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='FlowerXL',
        href='https://www.deviantart.com/flowerxl/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='dandonfuga',
        href='https://www.deviantart.com/dandonfuga/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='artgerm',
        href='https://www.deviantart.com/artgerm/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='OdangoDatte',
        href='https://www.deviantart.com/odango-datte/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='Disharmonica',
        href='https://www.deviantart.com/disharmonica/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='fredgdperry',
        href='https://www.deviantart.com/fredgdperry/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='raikoart',
        href='https://www.deviantart.com/raikoart/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='ohnips',
        href='https://www.deviantart.com/ohnips/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='fenixfatalist',
        href='https://www.deviantart.com/fenixfatalist/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='jagodibujaDA',
        href='https://www.deviantart.com/jagodibuja/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='CianYo',
        href='https://www.deviantart.com/cianyo/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='NOPEYS',
        href='https://www.deviantart.com/nopeys/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='SGTMADNESS',
        href='https://www.deviantart.com/sgtmadness/gallery/',
        emojis='💎🏮',
    ),
    feed(
        title='irine_meier',
        href='https://www.instagram.com/irine_meier/',
        emojis='💎🏮',
    ),
    feed(
        title='shinynesaea',
        href='https://www.instagram.com/shinynesaea/',
        emojis='💎🏮',
    ),
    feed(
        title='svetlana_gq',
        href='https://www.instagram.com/svetlana_gq/',
        emojis='💎🏮',
    ),
    feed(
        title='wildrosesstories',
        href='https://www.instagram.com/wildrosesstories/',
        emojis='💎🏮',
    ),
    feed(
        title='daynehenderson',
        href='https://www.instagram.com/daynehenderson/',
        emojis='💎🏮',
    ),
    feed(
        title='adrianova_ph',
        href='https://www.instagram.com/adrianova.ph/',
        emojis='💎🏮',
    ),
    feed(
        title='tsara_lunga',
        href='https://www.instagram.com/tsara.lunga/',
        emojis='💎🏮',
    ),
    feed(
        title='stellachuuuuu',
        href='https://www.instagram.com/stellachuuuuu/',
        emojis='💎🏮',
    ),
    feed(
        title='ropecandy',
        href='https://www.instagram.com/ropecandy/',
        emojis='💎🏮',
    ),
    feed(
        title='thefuelgirls',
        href='https://www.instagram.com/thefuelgirls/',
        emojis='💎🏮',
    ),
    feed(
        title='sister_sinister',
        href='https://www.instagram.com/sister_sinister/',
        emojis='💎🏮',
    ),
    feed(
        title='annet_morningstar',
        href='https://www.instagram.com/annet_morningstar/',
        emojis='💎🏮',
    ),
    feed(
        title='brutalcute',
        href='https://www.instagram.com/brutalcute/',
        emojis='💎🏮',
    ),
    feed(
        title='shproton',
        href='https://www.instagram.com/shproton/',
        emojis='💎🏮',
    ),
    feed(
        title='minu_lansak',
        href='https://www.instagram.com/minu_lansak/',
        emojis='💎🏮',
    ),
    feed(
        title='mspervology',
        href='https://www.instagram.com/mspervology/',
        emojis='💎🏮',
    ),
    feed(
        title='theattentionwhale',
        href='https://www.instagram.com/theattentionwhale/',
        emojis='💎🏮',
    ),
    feed(
        title='yarishnavideos',
        href='https://www.instagram.com/yarishnavideos/',
        emojis='💎🏮',
    ),
    feed(
        title='adamae_dono',
        href='https://www.instagram.com/adamae_dono/',
        emojis='💎🏮',
    ),
    feed(
        title='itsopalsnow',
        href='https://www.instagram.com/itsopalsnow/',
        emojis='💎🏮',
    ),
    feed(
        title='wrapashouse',
        href='https://www.instagram.com/wrapashouse/',
        emojis='💎🏮',
    ),
    feed(
        title='lucycatofficial',
        href='https://www.instagram.com/lucycatofficial/',
        emojis='💎🏮',
    ),
    feed(
        title='valtesseproductions',
        href='https://www.instagram.com/valtesseproductions/',
        emojis='💎🏮',
    ),
    feed(
        title='misskyliemarilyn',
        href='https://www.instagram.com/misskyliemarilyn/',
        emojis='💎🏮',
    ),
    feed(
        title='xetalatex',
        href='https://www.instagram.com/xetalatex/',
        emojis='💎🏮',
    ),
    feed(
        title='1nikoshka1',
        href='https://www.instagram.com/1nikoshka1/',
        emojis='💎🏮',
    ),
    feed(
        title='chris_chaisy',
        href='https://www.instagram.com/chris_chaisy/',
        emojis='💎🏮',
    ),
    feed(
        title='refusetobeusual_shoes',
        href='https://www.instagram.com/refusetobeusual_shoes/',
        emojis='💎🏮',
    ),
    feed(
        title='jannetincosplay',
        href='https://www.instagram.com/jannetincosplay/',
        emojis='💎🏮',
    ),
    feed(
        title='reflectivedesire',
        href='https://www.instagram.com/reflectivedesire/',
        emojis='💎🏮',
    ),
    feed(
        title='kymnonstop',
        href='https://www.instagram.com/kymnonstop/',
        emojis='💎🏮',
    ),
    feed(
        title='auauau',
        href='https://www.instagram.com/auauau/',
        emojis='💎🏮',
    ),
    feed(
        title='alex_cosplays',
        href='https://www.instagram.com/alex_cosplays/',
        emojis='💎🏮',
    ),
    feed(
        title='faerie_blossom',
        href='https://www.instagram.com/faerie_blossom/',
        emojis='💎🏮',
    ),
    feed(
        title='letitiawright',
        href='https://www.instagram.com/letitiawright/',
        emojis='💎🏮',
    ),
    feed(
        title='apple',
        href='https://www.instagram.com/apple/',
        emojis='💎🏮',
    ),
    feed(
        title='miakhalifa',
        href='https://www.instagram.com/miakhalifa/',
        emojis='💎🏮',
    ),
    feed(
        title='mk_ays',
        href='https://www.instagram.com/mk_ays/',
        emojis='🏮',
    ),
    feed(
        title='yarishna',
        href='https://www.instagram.com/yarishna/',
        emojis='💎🏮',
    ),
    feed(
        title='eeelyeee',
        href='https://www.instagram.com/eeelyeee/',
        emojis='💎🏮',
    ),
    feed(
        title='threnodyinvelvet',
        href='https://www.instagram.com/threnodyinvelvet/',
        emojis='💎🏮',
    ),
    feed(
        title='vivid_vision',
        href='https://www.instagram.com/vivid_vision/',
        emojis='🏮',
    ),
    feed(
        title='enahernandezh',
        href='https://www.instagram.com/enahernandezh/',
        emojis='💎🏮',
    ),
    feed(
        title='roga_na_noge',
        href='https://www.instagram.com/roga_na_noge/',
        emojis='💎🏮',
    ),
    feed(
        title='miyukicosplay',
        href='https://www.instagram.com/miyukicosplay/',
        emojis='💎🏮',
    ),
    feed(
        title='lvenok0311',
        href='https://www.instagram.com/lvenok0311/',
        emojis='💎🏮',
    ),
    feed(
        title='amiko_chan',
        href='https://www.instagram.com/amiko_chan/',
        emojis='💎🏮',
    ),
    feed(
        title='jennalynnmeowri',
        href='https://www.instagram.com/jennalynnmeowri/',
        emojis='💎🏮',
    ),
    feed(
        title='poisonne',
        href='https://www.instagram.com/poisonne/',
        emojis='💎🏮',
    ),
    feed(
        title='latex_lucy_official',
        href='https://www.instagram.com/latex_lucy_official/',
        emojis='💎🏮',
    ),
    feed(
        title='maryd_model',
        href='https://www.instagram.com/maryd.model/',
        emojis='💎🏮',
    ),
    feed(
        title='jennierubyjane',
        href='https://www.instagram.com/jennierubyjane/',
        emojis='💎🏮',
    ),
    feed(
        title='zaytseva_tasha',
        href='https://www.instagram.com/zaytseva_tasha/',
        emojis='💎🏮',
    ),
    feed(
        title='notcamdamage',
        href='https://www.instagram.com/notcamdamage/',
        emojis='💎🏮',
    ),
    feed(
        title='softbompark',
        href='https://www.instagram.com/softbompark/',
        emojis='💎🏮',
    ),
    feed(
        title='korean_girlgroups',
        href='https://www.instagram.com/korean_girlgroups/',
        emojis='💎🏮',
    ),
    feed(
        title='katelyn_runck',
        href='https://www.instagram.com/katelyn_runck/',
        emojis='💎🏮',
    ),
    feed(
        title='christian_gschweng',
        href='https://www.instagram.com/christian.gschweng/',
        emojis='💎🏮',
    ),
    feed(
        title='eosandy',
        href='https://www.instagram.com/eosandy_/',
        emojis='💎🏮',
    ),
    feed(
        title='katyuskamoonfox',
        href='https://www.instagram.com/katyuskamoonfox/',
        emojis='💎🏮',
    ),
    feed(
        title='ridd1e',
        href='https://www.instagram.com/ridd1e/',
        emojis='💎🏮',
    ),
    feed(
        title='navinigri',
        href='https://www.instagram.com/navinigri/',
        emojis='💎🏮',
    ),
    feed(
        title='jessicanigri',
        href='https://www.instagram.com/jessicanigri/',
        emojis='💎🏮',
    ),
    feed(
        title='enjinight',
        href='https://www.instagram.com/enjinight/',
        emojis='💎🏮',
    ),
    feed(
        title='harleylavey',
        href='https://www.instagram.com/harleylavey/',
        emojis='💎🏮',
    ),
    feed(
        title='b880156',
        href='https://www.instagram.com/b880156/',
        emojis='💎🏮',
    ),
    feed(
        title='disharmonica',
        href='https://www.instagram.com/disharmonica/',
        emojis='💎🏮',
    ),
    feed(
        title='aliciamariebody',
        href='https://www.instagram.com/aliciamariebody/',
        emojis='💎🏮',
    ),
    feed(
        title='raquelreedxo',
        href='https://www.instagram.com/raquelreedxo/',
        emojis='💎🏮',
    ),
    feed(
        title='saiwsaiwsaiwInsta',
        href='https://www.instagram.com/saiwsaiwsaiw/',
        emojis='💎🏮',
    ),
    feed(
        title='darealginavalentina',
        href='https://www.instagram.com/darealginavalentina/',
        emojis='💎🏮',
    ),
    feed(
        title='starfuckedmodel',
        href='https://www.instagram.com/starfuckedmodel/',
        emojis='💎🏮',
    ),
    feed(
        title='fenixfatalistInsta',
        href='https://www.instagram.com/fenixfatalist/',
        emojis='💎🏮',
    ),
    feed(
        title='kalinkafoxInsta',
        href='https://www.instagram.com/kalinkafox/',
        emojis='💎🏮',
    ),
    feed(
        title='kalinka_fox',
        href='https://www.instagram.com/kalinka.fox/',
        emojis='💎🏮',
    ),
    feed(
        title='allisonstokke',
        href='https://www.instagram.com/allisonstokke/',
        emojis='💎🏮',
    ),
    feed(
        title='michie_peachie',
        href='https://www.instagram.com/michie_peachie/',
        emojis='🏮',
    ),
    feed(
        title='endzaadair',
        href='https://www.instagram.com/endzaadair/',
        emojis='💎🏮',
    ),
    feed(
        title='garotabike',
        href='https://www.instagram.com/garotabike/',
        emojis='💎🏮',
    ),
    feed(
        title='martinwongphoto',
        href='https://www.instagram.com/martinwongphoto/',
        emojis='💎🏮',
    ),
    feed(
        title='purplemuffinz',
        href='https://www.instagram.com/purplemuffinz/',
        emojis='💎🏮',
    ),
    feed(
        title='martinwongcosplay',
        href='https://www.instagram.com/martinwongcosplay/',
        emojis='💎🏮',
    ),
    feed(
        title='armoredheartcosplay',
        href='https://www.instagram.com/armoredheartcosplay/',
        emojis='💎🏮',
    ),
    feed(
        title='eri_kitami',
        href='https://www.instagram.com/eri_kitami/',
        emojis='💎🏮',
    ),
    feed(
        title='bangbezInsta',
        href='https://www.instagram.com/bangbez/',
        emojis='💎🏮',
    ),
    feed(
        title='pedalingheroine',
        href='https://www.instagram.com/pedalingheroine/',
        emojis='💎🏮',
    ),
    feed(
        title='honkfu',
        href='https://www.instagram.com/honkfu/',
        emojis='💎🏮',
    ),
    feed(
        title='tudvaseva_sasha',
        href='https://www.instagram.com/tudvaseva_sasha/',
        emojis='💎🏮',
    ),
    feed(
        title='nana_the_shrimp',
        href='https://www.instagram.com/nana.the.shrimp/',
        emojis='💎🏮',
    ),
    feed(
        title='maxgrecke',
        href='https://www.instagram.com/maxgrecke/',
        emojis='💎🏮',
    ),
    feed(
        title='anna_cattish',
        href='https://www.instagram.com/anna_cattish/',
        emojis='💎🏮',
    ),
    feed(
        title='mjhiblenart',
        href='https://www.instagram.com/mjhiblenart/',
        emojis='💎🏮',
    ),
    feed(
        title='reya__sunshine',
        href='https://www.instagram.com/reya__sunshine/',
        emojis='💎🏮',
    ),
    feed(
        title='alysontabbitha',
        href='https://www.instagram.com/alysontabbitha/',
        emojis='💎🏮',
    ),
    feed(
        title='brittanya187',
        href='https://www.instagram.com/brittanya187/',
        emojis='💎🏮',
    ),
    feed(
        title='cutiepiesensei',
        href='https://www.instagram.com/cutiepiesensei/',
        emojis='💎🏮',
    ),
    feed(
        title='twiiic',
        href='https://www.instagram.com/twiiic/',
        emojis='💎🏮',
    ),
    feed(
        title='fit_with_iulia',
        href='https://www.instagram.com/fit.with.iulia/',
        emojis='🏮',
    ),
    feed(
        title='leanmachine21',
        href='https://www.instagram.com/leanmachine21/',
        emojis='💎🏮',
    ),
    feed(
        title='cristinacapron',
        href='https://www.instagram.com/cristinacapron/',
        emojis='🏮',
    ),
    feed(
        title='antonwolf1988',
        href='https://www.instagram.com/antonwolf1988/',
        emojis='💎🏮',
    ),
    feed(
        title='katyhearnvideos',
        href='https://www.instagram.com/katyhearnvideos/',
        emojis='💎🏮',
    ),
    feed(
        title='suzie_kb',
        href='https://www.instagram.com/suzie_kb/',
        emojis='🏮',
    ),
    feed(
        title='mashawakka',
        href='https://www.instagram.com/mashawakka/',
        emojis='💎🏮',
    ),
    feed(
        title='shirogane_sama',
        href='https://www.instagram.com/shirogane_sama/',
        emojis='💎🏮',
    ),
    feed(
        title='xandrastax',
        href='https://www.instagram.com/xandrastax/',
        emojis='💎🏮',
    ),
    feed(
        title='sawalee_r',
        href='https://www.instagram.com/sawalee.r/',
        emojis='💎🏮',
    ),
    feed(
        title='tianajoelle',
        href='https://www.instagram.com/tianajoelle/',
        emojis='🏮',
    ),
    feed(
        title='kayleeullom',
        href='https://www.instagram.com/kayleeullom/',
        emojis='💎🏮',
    ),
    feed(
        title='hannushka',
        href='https://www.instagram.com/_hannushka_/',
        emojis='💎🏮',
    ),
    feed(
        title='gainswithkathy',
        href='https://www.instagram.com/gainswithkathy/',
        emojis='🏋️🏮',
    ),
    feed(
        title='stef_fit',
        href='https://www.instagram.com/stef_fit/',
        emojis='💎🏮',
    ),
    feed(
        title='whitneyysimmons',
        href='https://www.instagram.com/whitneyysimmons/',
        emojis='🏮',
    ),
    feed(
        title='jillchristinefit',
        href='https://www.instagram.com/jillchristinefit/',
        emojis='🏋️🏮',
    ),
    feed(
        title='theartofmathew',
        href='https://www.instagram.com/theartofmathew/',
        emojis='💎🏮',
    ),
    feed(
        title='fitbeast',
        href='https://www.instagram.com/fitbeast/',
        emojis='💎🏮',
    ),
    feed(
        title='nonbinate',
        href='https://www.instagram.com/nonbinate/',
        emojis='💎🏮',
    ),
    feed(
        title='avantgeek',
        href='https://www.instagram.com/avantgeek/',
        emojis='🏮',
    ),
    feed(
        title='brittanyperilleee',
        href='https://www.instagram.com/brittanyperilleee/',
        emojis='🏮',
    ),
    feed(
        title='espana927',
        href='https://www.instagram.com/espana927/',
        emojis='🏮',
    ),
    feed(
        title='michelle_lewin',
        href='https://www.instagram.com/michelle_lewin/',
        emojis='💎🏮',
    ),
    feed(
        title='minafatale',
        href='https://www.instagram.com/minafatale/',
        emojis='💎🏮',
    ),
    feed(
        title='verabambilive',
        href='https://www.instagram.com/verabambilive/',
        emojis='💎🏮',
    ),
    feed(
        title='vikikacosta',
        href='https://www.instagram.com/vikikacosta/',
        emojis='💎🏮',
    ),
    feed(
        title='laurensimpson',
        href='https://www.instagram.com/laurensimpson/',
        emojis='💎🏮',
    ),
    feed(
        title='tmiller_fit',
        href='https://www.instagram.com/tmiller_fit/',
        emojis='💎🏮',
    ),
    feed(
        title='anita_herbert',
        href='https://www.instagram.com/anita_herbert/',
        emojis='💎🏮',
    ),
    feed(
        title='lisa__official',
        href='https://www.instagram.com/lisa__official/',
        emojis='💎🏮',
    ),
    feed(
        title='masher_xtr',
        href='https://www.instagram.com/masher_xtr/',
        emojis='💎🏮',
    ),
    feed(
        title='kyrapoh',
        href='https://www.instagram.com/kyrapoh/',
        emojis='💎🏮',
    ),
    feed(
        title='chelsvaccariello',
        href='https://www.instagram.com/chelsvaccariello/',
        emojis='🏋️🏮',
    ),
    feed(
        title='hasunoai',
        href='https://www.instagram.com/hasunoai/',
        emojis='💎🏮',
    ),
    feed(
        title='spcats_doremi',
        href='https://www.instagram.com/spcats_doremi/',
        emojis='💎🏮',
    ),
    feed(
        title='spiralcats_tasha',
        href='https://www.instagram.com/spiralcats_tasha/',
        emojis='💎🏮',
    ),
    feed(
        title='elvyshine',
        href='https://www.instagram.com/elvyshine/',
        emojis='💎🏮',
    ),
    feed(
        title='latexthrowback',
        href='https://www.instagram.com/latexthrowback/',
        emojis='💎🏮',
    ),
    feed(
        title='bast_model_life',
        href='https://www.instagram.com/bast_model_life/',
        emojis='💎🏮',
    ),
    feed(
        title='killers_story',
        href='https://www.instagram.com/killers_story/',
        emojis='💎🏮',
    ),
    feed(
        title='missmary_d',
        href='https://www.instagram.com/missmary.d/',
        emojis='💎🏮',
    ),
)
